### ISSUE TITLE
PmtMtd and subject with creditransfers

### ISSUE THREAD

**Issue by overwerk** [java-sepa-xml/java-sepa-xml#2]
Hi, thanks for work. Really helped me get things going.

I faced two minor issues:

1) According to this document (https://www.nordea.com/Images/36-262430/MIG-CAP_pain%20001.001.03_Payments_v_1.5.pdf) valid codes in the used standard (pain.001.001.03) are CHK and TRF. So I altered SEPA.Java and with TRF everything works fine.

2) When I created a credit transfer file the subject was left out. I altered the last lines in SEPACreditTransfer.java to nodeCdtTrfTxInf.append("RmtInf").append("Ustrd").value(transaction.getSubject());

From my understanding Remittance can't be set at all while using credit transfers.

Have a nice weekend

**Comment by java-sepa-xml** [comment]
Hi, thank you for reporting. I've applyed yout changes. Many thanks for contributing.
